name: app_actions
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
      # if test pass cps ${{github.repository}} to root@ip
      - name: Copy repo to VPS
        run: echo "${{  github.repository  }} ${{  secrets.OCEAN_PASS  }}"
